import {User} from "../models/chiefeat/users";

export const chiefs: User[] = [
    // Utilisateur 1
    {
        id: 1,
        pseudo: "JohnDoe",
        firstname: "John",
        lastname: "Doe",
        street: "Rue de la Paix",
        postalCode: "75001",
        email: "john.doe@example.com",
        phoneNumber: "0123456789",
        citiesId: 123,
        deliveryForTime: 30,
        password: "motdepasse123",
        siretCode: "SIRETCODE123",
        workplace: "Entreprise XYZ",
        rating: 4.5,
        user_description: "Je suis un utilisateur passionné par...",
        token: "TOKEN123",
        stripeAccountID: "STRIPEACCID123",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID123",
        picture: "https://exemple.com/picture.jpg",
        action_perimeter: 10,
        dateBirth: "1990-01-01",
        firebaseUid: "FIREBASEUID123",
        profileTypesId: 2,
        enable: true,
        addresses: "Adresse 1, Adresse 2",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    // Utilisateur 2
    {
        id: 2,
        pseudo: "JaneSmith",
        firstname: "Jane",
        lastname: "Smith",
        street: "Avenue des Fleurs",
        postalCode: "69002",
        email: "jane.smith@example.com",
        phoneNumber: "9876543210",
        citiesId: 456,
        deliveryForTime: 15,
        password: "password456",
        siretCode: "SIRETCODE456",
        workplace: "Entreprise ABC",
        rating: 3.8,
        user_description: "Passionate user with expertise in...",
        token: "TOKEN456",
        stripeAccountID: "STRIPEACCID456",
        stripeAccountFinalize: false,
        firebaseMessagingId: "FIREBASEMSGID456",
        picture: "https://exemple.com/picture2.jpg",
        action_perimeter: 20,
        dateBirth: "1985-05-10",
        firebaseUid: "FIREBASEUID456",
        profileTypesId: 1,
        enable: true,
        addresses: "Adresse 3, Adresse 4",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    // Utilisateur 3
    {
        id: 3,
        pseudo: "AliceJohnson",
        firstname: "Alice",
        lastname: "Johnson",
        street: "Rue du Commerce",
        postalCode: "13001",
        email: "alice.johnson@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 25,
        password: "azerty123",
        siretCode: "SIRETCODE789",
        workplace: "Entreprise QWE",
        rating: 4.2,
        user_description: "Passionate about entrepreneurship...",
        token: "TOKEN789",
        stripeAccountID: "STRIPEACCID789",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID789",
        picture: "https://exemple.com/picture3.jpg",
        action_perimeter: 15,
        dateBirth: "1992-07-15",
        firebaseUid: "FIREBASEUID789",
        profileTypesId: 2,
        enable: true,
        addresses: "Adresse 5, Adresse 6",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    // Utilisateur 4
    {
        id: 4,
        pseudo: "MikeBrown",
        firstname: "Mike",
        lastname: "Brown",
        street: "Main Street",
        postalCode: "90210",
        email: "mike.brown@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 20,
        password: "qwerty456",
        siretCode: "SIRETCODE987",
        workplace: "Entreprise ASDF",
        rating: 4.0,
        user_description: "Passionate about technology...",
        token: "TOKEN987",
        stripeAccountID: "STRIPEACCID987",
        stripeAccountFinalize: false,
        firebaseMessagingId: "FIREBASEMSGID987",
        picture: "https://exemple.com/picture4.jpg",
        action_perimeter: 12,
        dateBirth: "1988-11-25",
        firebaseUid: "FIREBASEUID987",
        profileTypesId: 1,
        enable: true,
        addresses: "Adresse 7, Adresse 8",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    // Utilisateur 5
    {
        id: 5,
        pseudo: "EmilyWhite",
        firstname: "Emily",
        lastname: "White",
        street: "Sunset Boulevard",
        postalCode: "90069",
        email: "emily.white@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 30,
        password: "password789",
        siretCode: "SIRETCODE654",
        workplace: "Entreprise ZXCV",
        rating: 4.7,
        user_description: "Food enthusiast and recipe creator...",
        token: "TOKEN654",
        stripeAccountID: "STRIPEACCID654",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID654",
        picture: "https://exemple.com/picture5.jpg",
        action_perimeter: 18,
        dateBirth: "1995-03-17",
        firebaseUid: "FIREBASEUID654",
        profileTypesId: 2,
        enable: true,
        addresses: "Adresse 9, Adresse 10",
        passwordResetToken: "",
        passwordResetExpires: null
    }
];

export const eaters: User[] = [
    {
        id: 6,
        pseudo: "SarahGreen",
        firstname: "Sarah",
        lastname: "Green",
        street: "Baker Street",
        postalCode: "SW1A 1AA",
        email: "sarah.green@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 20,
        password: "password123",
        siretCode: "SIRETCODE987",
        workplace: "Entreprise ABC",
        rating: 4.2,
        user_description: "Passionate about art and culture...",
        token: "TOKEN987",
        stripeAccountID: "STRIPEACCID987",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID987",
        picture: "https://example.com/picture6.jpg",
        action_perimeter: 15,
        dateBirth: "1993-09-12",
        firebaseUid: "FIREBASEUID987",
        profileTypesId: 2,
        enable: true,
        addresses: "Adresse 11, Adresse 12",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    {
        id: 7,
        pseudo: "DavidWilson",
        firstname: "David",
        lastname: "Wilson",
        street: "High Street",
        postalCode: "E1 7PT",
        email: "david.wilson@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 25,
        password: "password456",
        siretCode: "SIRETCODE654",
        workplace: "Entreprise XYZ",
        rating: 4.7,
        user_description: "Passionate about photography...",
        token: "TOKEN654",
        stripeAccountID: "STRIPEACCID654",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID654",
        picture: "https://example.com/picture7.jpg",
        action_perimeter: 20,
        dateBirth: "1987-06-25",
        firebaseUid: "FIREBASEUID654",
        profileTypesId: 1,
        enable: true,
        addresses: "Adresse 13, Adresse 14",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    {
        id: 8,
        pseudo: "OliviaBrown",
        firstname: "Olivia",
        lastname: "Brown",
        street: "Park Lane",
        postalCode: "W1K 7TN",
        email: "olivia.brown@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 30,
        password: "password789",
        siretCode: "SIRETCODE321",
        workplace: "Entreprise QWE",
        rating: 3.9,
        user_description: "Passionate about fashion and design...",
        token: "TOKEN321",
        stripeAccountID: "STRIPEACCID321",
        stripeAccountFinalize: false,
        firebaseMessagingId: "FIREBASEMSGID321",
        picture: "https://example.com/picture8.jpg",
        action_perimeter: 25,
        dateBirth: "1991-02-18",
        firebaseUid: "FIREBASEUID321",
        profileTypesId: 2,
        enable: true,
        addresses: "Adresse 15, Adresse 16",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    {
        id: 9,
        pseudo: "MichaelTaylor",
        firstname: "Michael",
        lastname: "Taylor",
        street: "Oxford Street",
        postalCode: "WC1A 1AA",
        email: "michael.taylor@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 15,
        password: "password123",
        siretCode: "SIRETCODE123",
        workplace: "Entreprise ASD",
        rating: 4.5,
        user_description: "Passionate about sports and fitness...",
        token: "TOKEN123",
        stripeAccountID: "STRIPEACCID123",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID123",
        picture: "https://example.com/picture9.jpg",
        action_perimeter: 30,
        dateBirth: "1989-10-05",
        firebaseUid: "FIREBASEUID123",
        profileTypesId: 1,
        enable: true,
        addresses: "Adresse 17, Adresse 18",
        passwordResetToken: "",
        passwordResetExpires: null
    },
    {
        id: 10,
        pseudo: "SophiaClark",
        firstname: "Sophia",
        lastname: "Clark",
        street: "Regent Street",
        postalCode: "W1B 2EL",
        email: "sophia.clark@example.com",
        phoneNumber: "5555555555",
        citiesId: 789,
        deliveryForTime: 25,
        password: "password456",
        siretCode: "SIRETCODE456",
        workplace: "Entreprise ZXC",
        rating: 4.0,
        user_description: "Passionate about travel and exploration...",
        token: "TOKEN456",
        stripeAccountID: "STRIPEACCID456",
        stripeAccountFinalize: true,
        firebaseMessagingId: "FIREBASEMSGID456",
        picture: "https://example.com/picture10.jpg",
        action_perimeter: 18,
        dateBirth: "1990-08-22",
        firebaseUid: "FIREBASEUID456",
        profileTypesId: 2,
        enable: true,
        addresses: "Adresse 19, Adresse 20",
        passwordResetToken: "",
        passwordResetExpires: null
    }
];

