export const AgeInterval : string[] = ["Moins de 18 ans", "18 - 25 ans", "25 - 40 ans", "Plus de 40 ans"];

export const BkoQuartersList : string[] = [
    'Kalaban-Coura',
    'Faladie',
    'Lafiabougou',
    'Hamdallaye',
    'Bolibana',
    'ACI 2000',
    'Badalabougou',
    'Quartier-Mali',
    'Bozola',
    'Cité du Niger',
    'Kalaban-Coro',
    'Bagadadji',
    'Quinzabougou',
    'Bamako-Coura',
    'Bacodji-Aci',
    'Golf',
    'Torokorobougou',
    'Niarela',
    'Wolofoboubou',
    'Médine-Coura',
    'Korofina',
    'Badjalan',
    'ATT-bougou',
    'Tominkorobougou',
    'Sebenikoro',
    'Darsalam',
    'Djicoroni-Para',
    'Djelibougou',
    'Hippodrome',
    'Missira',
    'Banconi',
    'Boulkassoumbougou',
    'Sikôrôni',
    'Magnambougou',
    'Banakabougou',
    'Nimakôrô',
    'Sokonikô',
    'Yirimadio',
    'Koulouba',
    'Sabalibougou',
    'Dravéla',
    'Daoudabougou',
    'Base Aerienne',
    'Titibougou',
    'Moribabougou'
]
